#Database configuration
#Mon Oct 06 16:00:04 IST 2025
driver=com.mysql.cj.jdbc.Driver
pass=
url=jdbc\:mysql\://127.0.0.1\:3306/bookdiary?useSSL\=false&allowPublicKeyRetrieval\=true&serverTimezone\=UTC
user=root
